// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from docs directory structure
    },
  ],
};

module.exports = sidebars;